baseURL: "https://ofdma.cn/"
languageCode: zh-cn
title: "正交频分多址(OFDMA)"
theme: "d"
enableGitInfo: true
menu:
  main:
    - name: "<u>H</u>ome"
      url: /
      weight: 1
    - name: "<u>T</u>ags"
      url: "/tags"
      weight: 2

params:
  description: "正交频分多址(Orthogonal Frequency Division Multiple Access，OFDMA)是无线通信系统中的一种多重接取技术，WiMax、LTE都采用OFDMA。"

markup:
  highlight:
    codeFences: true
    style: bw
    lineNumbersInTable: false
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - html
    - rss
    - json
  page:
    - html
